modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="origins"
version="${version}"
displayName="Origins"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://apace100.github.io/origins-fabric"
logoFile="origins_icon.png"
#credits=""
authors="Apace"
description='''
This mod adds several origins with passive abilities to the game, which you can choose from at the beginning of the game.
'''

[[dependencies.origins]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36.1.3,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="cloth-config"
mandatory=true
versionRange="[4.11.14,)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="architectury"
mandatory=true
versionRange="[1.10.140,)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="caelus"
mandatory=true
versionRange="[1.16.5-2.1.1.0,)"
ordering="NONE"
side="BOTH"

#Forge prevents access to non-declared dependencies

[[dependencies.origins]]
modId="better_diving"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"